# -*- coding: utf-8 -*-
{
    "name": "Mezztt Mercado Pago QR",
    "summary": "Integración de Mercado Pago QR dinámico para el Punto de Venta",
    "description": """
        Permite configurar credenciales de Mercado Pago y genera órdenes de QR dinámico
        desde el POS de Odoo para operar con terminales de autoservicio.
    """,
    "version": "1.0.0",
    "author": "AutoGenerated",
    "website": "https://example.com",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "depends": [
        "point_of_sale",
        "web",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_view.xml",
        "views/pos_payment_method_view.xml",
    ],
    "assets": {
        "point_of_sale.assets": [
            "mezztt/static/src/css/mp_qr_styles.css",
            "mezztt/static/src/xml/mp_qr_templates.xml",
            "mezztt/static/src/js/mp_pos_models.js",
            "mezztt/static/src/js/mp_qr_popup.js",
            "mezztt/static/src/js/mp_payment_screen.js",
        ],
    },
    "installable": True,
    "application": False,
}
